function AISummary({ summary }) {
  return (
    <div className="card" style={{ padding: 32 }}>
      <div className="section-title">
        <span>✦</span> AI Summary
      </div>
      <div style={{
        position: 'relative',
        paddingLeft: 20,
        borderLeft: '2px solid rgba(139,92,246,0.4)'
      }}>
        <p style={{
          color: 'rgba(255,255,255,0.7)',
          fontSize: 16,
          lineHeight: 1.9,
          fontStyle: 'italic'
        }}>
          {summary}
        </p>
        <div style={{
          marginTop: 16,
          display: 'flex',
          alignItems: 'center',
          gap: 8
        }}>
          <div style={{
            width: 20, height: 20, borderRadius: '50%',
            background: 'linear-gradient(135deg, #a78bfa, #60a5fa)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 10
          }}>✦</div>
          <span style={{ fontSize: 12, color: 'rgba(255,255,255,0.25)' }}>
            Generated by Groq AI
          </span>
        </div>
      </div>
    </div>
  )
}

export default AISummary